#ShootOFF Configuration
#Tue Aug 26 20:15:32 PDT 2025
shootoff.webcams.distances=
shootoff.virtualmagazine.use=false
shootoff.arena.calibrated.exposure=true
shootoff.markerradius=4
shootoff.webcams=
shootoff.errorreporting=false
shootoff.arena.notified.perspective=false
shootoff.virtualmagazine.capacity=7
shootoff.arena.show.markers=false
shootoff.malfunctions.probability=10.0
shootoff.redlasersound=/home/ricky/dev/ShootOFF/sounds/walther_ppq.wav
shootoff.ignorelasercolor=None
shootoff.firstrun=false
shootoff.malfunctions.use=false
shootoff.arena.calibrated.behavior=ONLY_IN_BOUNDS
shootoff.ipcams=
shootoff.greenlasersound=/home/ricky/dev/ShootOFF/sounds/walther_ppq.wav
shootoff.webcams.recording=
shootoff.diagnosticmessages.chime.muted=
shootoff.redlasersound.use=false
shootoff.greenlasersound.use=false
