name: Build Gradle project

on:
  push:
    branches: [ 'gradle9', 'master' ]
  pull_request:
    branches: [ 'gradle9', 'master' ]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libglib2.0-0 libudev1 libgstreamer1.0-0 libgstreamer-plugins-base1.0-0 libv4l-0

      - name: Run assemble
        run: ./gradlew assemble

      - name: Build Dependents
        run: xvfb-run -a ./gradlew buildDependents
